# Generated by Django 3.2.7 on 2021-10-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_wish',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_wish',
            new_name='user_id',
        ),
    ]
