# Generated by Django 3.2.7 on 2021-10-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
